# Generated by Django 4.1 on 2025-05-26 16:23

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemahall',
            name='image',
            field=models.ImageField(null=True, upload_to=cinema.models.image_file_path),
        ),
    ]
