# Generated by Django 4.1 on 2025-05-27 13:52

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_cinemahall_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemahall',
            name='image',
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(null=True, upload_to=cinema.models.image_file_path),
        ),
    ]
